import React, { useMemo, useRef, useState } from 'react';
import axios from 'axios';
import { CheckCircle2, CloudUpload, Download, FileText, FolderOpen, Grid2X2, List, Search, Trash2, UploadCloud, X, XCircle } from 'lucide-react';

const API_URL='http://localhost:5000/api';
const MAX=10*1024*1024;
const TYPES=['image/jpeg','image/png','image/webp','application/pdf'];
const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};

export default function App(){
 const input=useRef(); const [file,setFile]=useState(null),[preview,setPreview]=useState(''),[items,setItems]=useState([]),[drag,setDrag]=useState(false),[progress,setProgress]=useState(0),[state,setState]=useState('idle'),[msg,setMsg]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[view,setView]=useState('grid'),[modal,setModal]=useState(null);
 const stats=useMemo(()=>({total:items.length,images:items.filter(x=>x.type?.startsWith('image/')).length,docs:items.filter(x=>x.type==='application/pdf').length,size:items.reduce((a,x)=>a+x.size,0)}),[items]);
 const visible=items.filter(x=>(filter==='all'||(filter==='images'&&x.type.startsWith('image/'))||(filter==='documents'&&x.type==='application/pdf'))&&x.name.toLowerCase().includes(query.toLowerCase()));
 const pick=f=>{if(!f)return;const e=!TYPES.includes(f.type)?'Unsupported type. Use JPG, PNG, WEBP or PDF.':f.size>MAX?'File is larger than the 10 MB limit.':'';if(e){setState('error');setMsg(e);return}if(preview)URL.revokeObjectURL(preview);setFile(f);setPreview(f.type.startsWith('image/')?URL.createObjectURL(f):'');setProgress(0);setState('ready');setMsg('')};
 const upload=async()=>{if(!file)return;const d=new FormData();d.append('file',file);try{setState('uploading');const r=await axios.post(`${API_URL}/upload`,d,{onUploadProgress:e=>e.total&&setProgress(Math.round(e.loaded/e.total*100))});setItems(a=>[{...r.data.file,uploadedAt:new Date().toLocaleTimeString()},...a]);setState('success');setMsg('Upload complete — file is stored and ready to use.');setFile(null);setPreview('');if(input.current)input.current.value=''}catch(e){setState('error');setMsg(e.response?.data?.message||'Upload failed. Make sure the backend is running.')}};
 const remove=()=>{if(preview)URL.revokeObjectURL(preview);setFile(null);setPreview('');setState('idle');setMsg('');if(input.current)input.current.value=''};
 return <div className="shell"><header><div className="brand"><div className="mark"><CloudUpload size={20}/></div><div><b>FileVault</b><small>Upload Hub</small></div></div><span className="secure"><i/> Local storage</span></header><main>
 <section className="hero"><div><label>FILE MANAGEMENT</label><h1>Your upload workspace.</h1><p>Upload, preview and manage your files from one clean workspace.</p></div><button className="primary" onClick={()=>input.current?.click()}><UploadCloud size={17}/> New upload</button></section>
 <div className="stats"><div><span>Total files</span><b>{stats.total}</b></div><div><span>Images</span><b>{stats.images}</b></div><div><span>Documents</span><b>{stats.docs}</b></div><div><span>Storage used</span><b>{bytes(stats.size)}</b></div></div>
 <section className="card uploader"><div className={'drop '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);pick(e.dataTransfer.files?.[0])}} onClick={()=>input.current?.click()}><input ref={input} hidden type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>pick(e.target.files?.[0])}/><div className="upload-icon"><UploadCloud size={27}/></div><h2>{drag?'Drop it here':'Drag & drop your file here'}</h2><p>or click to browse from your computer</p><span className="browse"><FolderOpen size={15}/> Browse files</span><small>JPG, PNG, WEBP or PDF · Maximum 10 MB</small></div>
 {msg&&<div className={'notice '+(state==='error'?'bad':'good')}>{state==='error'?<XCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{msg}</span><button onClick={()=>setMsg('')}><X size={14}/></button></div>}
 {file&&<div className="queue"><div className="thumb">{preview?<img src={preview} alt="preview"/>:<FileText size={28}/>}</div><div className="qinfo"><b>{file.name}</b><span>{bytes(file.size)} · Ready to upload</span>{state==='uploading'&&<><div className="prow"><span>Uploading</span><b>{progress}%</b></div><div className="track"><i style={{width:`${progress}%`}}/></div></>}</div><button className="ghost" onClick={remove}><Trash2 size={17}/></button><button className="primary upload" onClick={upload} disabled={state==='uploading'}>{state==='uploading'?`${progress}%`:'Upload'}</button></div>}
 </section>
 <section className="library-head"><div><label>LIBRARY</label><h2>Recent uploads</h2></div><div className="tools"><div className="search"><Search size={15}/><input placeholder="Search files..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="filters">{['all','images','documents'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="views"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={14}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={14}/></button></div></div></section>
 {visible.length===0?<div className="empty card"><FolderOpen size={30}/><b>{items.length?'No matching files':'No uploads yet'}</b><span>{items.length?'Try another search or filter.':'Your uploaded files will appear here.'}</span></div>:<section className={view==='grid'?'grid':'list'}>{visible.map(x=><article className="file card" key={x.id||x.storedName}><div className="visual">{x.type.startsWith('image/')?<img src={x.url} alt={x.name}/>:<FileText size={34}/>}<em>{x.type==='application/pdf'?'PDF':'IMAGE'}</em></div><div className="fbody"><b title={x.name}>{x.name}</b><span>{bytes(x.size)} · {x.uploadedAt}</span><div className="actions">{x.type.startsWith('image/')&&<button onClick={()=>setModal(x)}>Preview</button>}<a href={x.url} target="_blank" rel="noreferrer">Open</a><a href={x.url} download><Download size={13}/> Download</a></div></div></article>)}</section>}
 <footer><b>FileVault</b><span>React · Express · Multer · Local Storage</span></footer></main>
 {modal&&<div className="backdrop" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><img src={modal.url} alt={modal.name}/><b>{modal.name}</b><span>{bytes(modal.size)} · Image</span><a href={modal.url} download className="primary"><Download size={15}/> Download file</a></div></div>}
 </div>}
